### PR TITLE
Add volume difference plotting scripts

### PR DESCRIPTION
**Pull request by clane9**
## Description

This PR adds scripts for visualizing the difference between individual Nifti volumes (`plot_nii_difference.py`) and 4d Nifti volume series (`plot_nii_difference_movie.py`).

I'm also adding a `viz_utils.py` module to contain shared utils. But note that in order for scripts to import from `viz_utils.py`, the `code/` directory must be on the user's python path.

### CODE REVIEW

**Comment by gkiar** [comment]
Looks awesome! Would adding and `__init__.py` make it so that the directory is automatically recognized for source files by each of these scripts? If so, may make it easier to use for people who don't want to (or forget to) mess with their `PYTHON_PATH` variable.

**Review by shnizzedy — APPROVED** [review]
> Would adding and __init__.py make it so that the directory is automatically recognized for source files by each of these scripts? If so, may make it easier to use for people who don't want to (or forget to) mess with their PYTHON_PATH variable.

I think adding an `__init__.py` to `code` is a good idea, but I also don't see where any of this would require modifying `PYTHON_PATH` if running from within `code`

I'm almost always in favor of modularization, but I'd also be happy with this being merged in as-is

**Comment by gkiar** [comment]
Right — I suppose adding an `__init__.py` would just allow running from the root of the repository, as well? I'm happy either way

**Comment by shnizzedy** [comment]
> adding an __init__.py would just allow running from the root of the repository, as well?

Or from any arbitrary location if the package is installed, like if you want to run from where your data are instead of from where this code is

**Comment by clane9** [comment]
I never quite remember how the module search path works. But I tested the script out as is from a random directory and it worked fine. Maybe when a script is run as `"__main__"`, its parent directory is automatically included in the path?

I agree that the less we ask of users of these "quick and easy" scripts the better.

**Comment by gkiar** [comment]
Sweet,I'll merge. Thanks, Connor!

**Pull request merged**
